70 crear el componente modal
frontendcafe/water-call-for-papers pull request #100
Opened 2022-08-25 17:43 UTC by ErikGIovani

Componente Modal creado

2022-08-26 15:24 UTC, nykka requested changes
Muy bueno Erik!!! Le faltan un par de detalles nomás 🎉

2022-08-26 15:24 UTC, nykka commented on stories/Modal/Modal.tsx
> +              <Dialog.Panel className="w-full max-w-[407px] transform overflow-hidden rounded-xl p-4 bg-gray-500 shadow-xl transition-all">
Tratemos de no usar numeros arbitrarios. `max-w-md` es igual a 448px

2022-08-26 15:24 UTC, nykka commented on stories/Modal/Modal.tsx
> +                <div className="w-[375px] rounded-xl bg-white">
`w-96` es igual a 384px

2022-08-26 15:24 UTC, nykka commented on stories/Modal/Modal.tsx
> +                  <div className="flex p-[15px]">{children}</div>
`p-3.5` es igual a 15px

2022-08-26 15:24 UTC, nykka commented on stories/Modal/Modal.stories.tsx
> +      <Button backgroundColor="bg-blue-500" onClick={() => setIsOpen(true)} label="Activar Modal" />
Tendrias que actualizar tu branch con lo último de main así podes usar el componente `Button` nuevo!

2022-08-26 15:24 UTC, nykka commented on stories/Modal/Modal.tsx
> +  useEffect(() => {
Esto no me convence, pero dejame pensar por que. jaja

2022-09-01 12:45 UTC, franmper commented on stories/Modal/Modal.tsx
> +  useEffect(() => {
por que esto es necesario?

2022-09-01 12:46 UTC, franmper commented on stories/Modal/Modal.tsx
> +        as="div"
esta prop es como default un div creo

2022-09-02 20:44 UTC, nykka commented
@ErikGIovani En vez de:
`if (size == "large") {
    width = "max-w-[608px]";
  } else if (size == "medium") {
    width = "max-w-[360px]";
  }`
Mejor:
`
const modalWidth = {
  large: "max-w-[608px]",
  medium: "max-w-[360px]",
};
`
Y después en el elemento, en vez de renderizar `${width}`, haces `${modalWidth[size]}`
Por otro lado, si es posible, usa los tamaños que trae tailwind (aunque no sean exactos).

2022-09-02 20:47 UTC, nykka requested changes
Esto se ve genial! Te deje un comentario de algo a mejorar. Por otro lado creo que la X para cerrar el modal no es la misma del diseño. Se ve espectacular!

2022-09-06 00:48 UTC, franmper approved these changes

2022-09-06 20:10 UTC, nykka approved these changes
LGTM!!!

2022-09-07 00:26 UTC, merged