add notifications component
frontendcafe/water-call-for-papers pull request #104
Opened 2022-08-26 15:20 UTC by TonyMckes

Issue #16

Se agrego componente de alertas/notificaciones

2022-08-26 17:49 UTC, nykka requested changes
Esto está genial Tony!
Lamentablemente parece que descartaron los diseños que puse en el issue, y ahora quedaron así:
<img width="615" alt="Screen Shot 2022-08-26 at 14 46 10" src="https://user-images.githubusercontent.com/8450941/186962836-70d9f088-4188-48eb-83f8-29448215eefd.png">
Con lo cual habria que actualizar un poco lo que ya hiciste. Voy a adjuntar en el issue mas imagenes y links a Figma.

2022-08-26 17:49 UTC, nykka commented on stories/Alert/Alert.tsx
> +  "aria-live": "off" | "polite" | "assertive";
Estoy pensnado si esta prop debería ser optativa, ya que puede que en alguno de sus usos no se actualice su contenido nunca. Que pensas? Por otro lado creo que `aria-live` siempre tiene que ir acompañado por el tag `role`.

2022-08-26 23:28 UTC, TonyMckes commented on stories/Alert/Alert.tsx
> +  "aria-live": "off" | "polite" | "assertive";
Hmm.. Se me ocurre extender a `HTMLAttributes<HTMLDivElement>` y asi tener todos los atributos disponibles, y se podrian ir agregando como `required` a medida que se vaya necesitando

2022-08-30 13:36 UTC, TonyMckes commented on stories/Alert/Alert.tsx
> +  "aria-live": "off" | "polite" | "assertive";
Interesante.. vere como puedo hacer eso

2022-08-30 19:23 UTC, franmper approved these changes

2022-09-01 12:39 UTC, merged