66 crear el componente accordion
frontendcafe/water-call-for-papers pull request #106
Opened 2022-08-28 14:08 UTC by yolitzr

[Issue 66](https://github.com/frontendcafe/water-call-for-papers/issues/66)

Se crea el componente Accordion, y se agrega componente InputText y Textarea en el primer Item del tab , quedan pendiente los componente de los otros dos item.

Se agrega un useState con value para el InputText, se puede mejorar y crear una lógica cuando este listo la info del back para el editar el value del input.

2022-08-29 17:11 UTC, franmper requested changes
Te dejo unos comments yolit, saludos!

2022-08-29 17:11 UTC, franmper commented on stories/Accordion/Accordion.tsx
> +                  />
Todo lo que esta dentro del panel deberia ser uin `children` arbitrario que lo agregue la persona que ustilice el componente

2022-08-29 17:11 UTC, franmper commented on stories/Accordion/Accordion.tsx
> +                  />
un ejemplo de esto es el componente `Button` por ejemplo

2022-08-29 17:11 UTC, franmper commented on stories/Accordion/Accordion.tsx
> +  const onCreate = () => {};
Para que se utilizarian estas dos funciones `onSave` y `onCreate`. Tienen sentido qeu esten?

2022-08-29 17:11 UTC, franmper commented on stories/Input/InputText.tsx
> +            props.visible
Todo el codigo del `useState` y del `value` no deberia ser cambiado por que entiendo que el uso de esto va a ser por fuera del componente. Guarda con eliminar codigo de componentes sin consultar por que es muy poisible que haya una justificacion de por que se hizo asi.

2022-08-29 17:11 UTC, franmper commented on stories/Accordion/Accordion.tsx
> +    </div>
esto por que esta duplicado? posiblemente hubo una confusion entre hacer el componente y la pantalla?

2022-08-30 17:02 UTC, TonyMckes commented on stories/Accordion/Accordion.tsx
> +  const onCreate = () => {};
Ah si... sobre esas funciones! 
@franmper el boton tiene `onClick` como `required`. @LPRegen me comento que hizo el cambio en el PR #108 para que sea `opcional`, toca ver si se aprueba...

@yolitzr te etiqueto para que estes al tanto :smile:

2022-08-30 17:09 UTC, yolitzr commented on stories/Accordion/Accordion.tsx
> +                  />
Vale, ahí lo cambio!!

2022-08-30 17:11 UTC, yolitzr commented on stories/Accordion/Accordion.tsx
> +  const onCreate = () => {};
Pues pensé que al tener los botones de guardar y crear se debería de agregar la lógica para que hagan esas funciones, por eso los deje ya listo. Aunque claro también es lo que menciona @TonyMckes , hay muhcos valores que eran required y los coloque para no tocar el componente de otros de los chiques

2022-08-30 17:11 UTC, yolitzr commented on stories/Input/InputText.tsx
> +            props.visible
No entendí esta parte, si quieres después en un momento me lo explicas.

2022-08-30 17:12 UTC, yolitzr commented on stories/Accordion/Accordion.tsx
> +    </div>
No entendí esta parte, pero no deberían de ir entonces?

2022-09-02 20:54 UTC, nykka requested changes
Esta muy bueno! Te deje unos comentarios de unos detalles, pero en general esta perfecto!

2022-09-02 20:54 UTC, nykka commented on stories/Accordion/Accordion.tsx
> +            <Disclosure.Button className="flex w-full justify-between items-center py-2 rounded-md bg-primary-50 text-primary-700 text-left font-semibold hover:bg-primary-100 focus:border-[1.5px] foc
Ojo que el borde no puede ser de 1.5, sino de 1 o 2. Dejemos el que visualmente se aproxime al diseño.

2022-09-02 20:54 UTC, nykka commented on stories/Accordion/Accordion.tsx
> +              <div>
Creo que este `div` que wrappea `Disclosure.Panel` podria eliminarse

2022-09-05 14:34 UTC, franmper commented
Creo que quedaria solo resolver el conflicto @yolitzr  y estaría listo para aprobar y mergear!

2022-09-05 16:33 UTC, franmper approved these changes

2022-09-05 17:45 UTC, TonyMckes approved these changes

2022-09-06 20:11 UTC, nykka approved these changes
LGTM!!!

2022-09-06 21:01 UTC, merged