74 crear el componente navigation drawer
frontendcafe/water-call-for-papers pull request #107
Opened 2022-08-28 19:30 UTC by TonyMckes

Issue #74 

Se agrego el layout principal del sidebar drawer. WIP

#### Por hacer/revisar
- [ ] Storybook stories
- [X] Logo (required)
- [ ] Toggler button (required): En desktop el menu va a estar siempre abierto y se va a cerrar apretando un boton para cerrar (agregarlo aunque no este por ahora en el diseño). En mobile se abre y cierra haciendo click en el icono hamburguesa.
- [ ] Primary Navigation (required)
- [ ] Secondary Navigation (required)

#### Observaciones importantes!
- [X] Tiene que ser navegable usando el teclado
- [ ] Usando el teclado, cuando llega al ultimo link, tiene que volver al primero (focus trap)
- [ ] En mobile, cuando se abre, el focus debe estar en el boton para cerrar el menu.

#### Los estados que va a tener cada uno de los links del Menu son:
- [ ] Disabled
- [X] Hover
- [ ] Active
- [X] Focus

#### Desktop: main content behavior
[video-2022-08-28_15.24.52.webm](https://user-images.githubusercontent.com/78808163/187091155-65818095-1172-45b8-9db1-0e7b27995fc5.webm)

2022-09-02 21:15 UTC, nykka requested changes
@TonyMckes esto esta genial!!! Te deje un par de comentarios sobre algunos detalles.
Aparte te comparto este video para que veas como se anuncian las cosas con Voice Over para que veas lo que comento del label y el aria hidden: https://www.awesomescreenshot.com/video/10866188?key=f49530008d29e89cb3c978d7905c96cc

2022-09-02 21:15 UTC, nykka commented on stories/SidebarDrawer/SidebarDrawer.tsx
> +      <nav
Aca le agregaria `aria-expanded` y que sea `true` cuando esta abierto y `false` cuando esta cerrada
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded

2022-09-02 21:15 UTC, nykka commented on stories/SidebarDrawer/SidebarDrawer.tsx
> +        className={tw(
No entiendo por que tener esta función `tw()` en vez de pasar directamente la cadena de classes como un `string`

2022-09-02 21:15 UTC, nykka commented on stories/SidebarDrawer/SidebarDrawer.tsx
> +        <Button
Quizá seria mejor que el label cambie de "abrir menu" a "cerrar menu" de acuerdo al state

2022-09-02 21:15 UTC, nykka commented on stories/SidebarDrawer/IconContainer.tsx
> +    <span className="flex-shrink-0 inline-flex" {...props}>
Acá agregaria un aria hidden ya que es confuso cuando es anunciado por el lector de pantallas

2022-09-03 22:34 UTC, TonyMckes commented
@nykka tuve que agregar un `useEffect` para evitar que el menu inicie abierto en mobile (tambien ayuda con los condicionales para la accesibilidad).

El problema es que ahora inicia con una animacion (se expande) el desktop, se me ocurrio guardar ese `boolean` en el `localStorate` para evitar que eso pase cada vez que se recargue la pagina... que te parece?

2022-09-05 14:32 UTC, franmper commented
> @nykka tuve que agregar un `useEffect` para evitar que el menu inicie abierto en mobile (tambien ayuda con los condicionales para la accesibilidad).
> 
> El problema es que ahora inicia con una animacion (se expande) el desktop, se me ocurrio guardar ese `boolean` en el `localStorate` para evitar que eso pase cada vez que se recargue la pagina... que te parece?

Podriamos utilizar un `Context` para esto?

2022-09-05 15:18 UTC, TonyMckes commented
> > @nykka tuve que agregar un `useEffect` para evitar que el menu inicie abierto en mobile (tambien ayuda con los condicionales para la accesibilidad).
> > El problema es que ahora inicia con una animacion (se expande) el desktop, se me ocurrio guardar ese `boolean` en el `localStorate` para evitar que eso pase cada vez que se recargue la pagina... que te parece?
> 
> Podriamos utilizar un `Context` para esto?

Perdon, no entendi... Dices como un `Context` global? :thinking: 

Seria genial que `window` estuviera definido al iniciar el `useState` pero nou

2022-09-06 00:52 UTC, franmper commented
> > > @nykka tuve que agregar un `useEffect` para evitar que el menu inicie abierto en mobile (tambien ayuda con los condicionales para la accesibilidad).
> > > El problema es que ahora inicia con una animacion (se expande) el desktop, se me ocurrio guardar ese `boolean` en el `localStorate` para evitar que eso pase cada vez que se recargue la pagina... que te parece?
> > 
> > 
> > Podriamos utilizar un `Context` para esto?
> 
> Perdon, no entendi... Dices como un `Context` global? 🤔
> 
> Seria genial que `window` estuviera definido al iniciar el `useState` pero nou

sip, decia un context global, igual lo dije sin ver mucho, capaz me equivoco.

2022-09-06 01:22 UTC, TonyMckes commented
> > > > @nykka tuve que agregar un `useEffect` para evitar que el menu inicie abierto en mobile (tambien ayuda con los condicionales para la accesibilidad).
> > > > El problema es que ahora inicia con una animacion (se expande) el desktop, se me ocurrio guardar ese `boolean` en el `localStorate` para evitar que eso pase cada vez que se recargue la pagina... que te parece?
> > > 
> > > 
> > > Podriamos utilizar un `Context` para esto?
> > 
> > 
> > Perdon, no entendi... Dices como un `Context` global? thinking
> > Seria genial que `window` estuviera definido al iniciar el `useState` pero nou
> 
> sip, decia un context global, igual lo dije sin ver mucho, capaz me equivoco.

hmm.. la cosa es guardar el estado del sidebar para que sea persistente (solo en desktop)...
con el `Context` se puede, mi pregunta seria si debo usarlo jeje

2022-09-09 09:32 UTC, nicolashzmor requested changes

2022-09-09 09:32 UTC, nicolashzmor commented on stories/SidebarDrawer/useSidebarReducer.ts
> +const reducer = (state: SidebarState, { type }: DispatchAction) => {
Usaría algún nombre un poco más declarativo que "reducer". 
Es una buena práctica en mi opinión no nombrar las cosas en función del patrón de diseño que implementan.
Podría ser _sidebarStateCalculator_ o algo así? En definitiva, independientemente de quién y cómo usen esto, esta función lo que hace es recibir un estado y un trigger (en este caso con la propiedad _type_) y en función de eso define un nuevo estado del sidebar.

2022-09-09 09:32 UTC, nicolashzmor commented on stories/SidebarDrawer/useSidebarReducer.ts
> +  return { sidebar, dispatch };
Al comentario de arriba también se puede agregar el _dispatch_ y el _sidebar_.

2022-09-09 09:32 UTC, nicolashzmor commented on stories/SidebarDrawer/useSidebarReducer.ts
> +        status: !status,
Status que representa? Porque para ser un boolean, status parece muy genérico.

2022-09-09 10:09 UTC, TonyMckes commented
Gracias por el feedback @nicolashzmor!

Por ahora creo que esta version con el `useReducer` sera descartada porque aparenta ser muy compleja.
Aunque ahora realmente no sabria como manejar los diferentes estados para la accesibilidad de forma simple :thinking:

2022-09-13 12:52 UTC, nykka approved these changes
Tony vamos asi como está y despues vemos como resolver lo del reducer.

2022-09-13 15:09 UTC, TonyMckes commented
> Tony vamos asi como está y despues vemos como resolver lo del reducer.

Me parece bien! :+1:

2022-09-15 13:52 UTC, TonyMckes commented
Hola @nicolashzmor! El otro dia hice los cambios que me pediste y me olvide avisar que se decidió merger, espero que se pueda entender un poco mejor lo que ocurre con el reducer jejee

2022-09-15 21:54 UTC, merged