Feat/crear componente clipboard
frontendcafe/water-call-for-papers pull request #110
Opened 2022-08-29 19:48 UTC by JairDev

Issue #68 
Los requerimientos de Focus, Active y Disabled, por los momentos no los agregué porque quiero que estén seguros que este componente debe ser un botón, en principio era un input, lo conversé con nikka y me sugirió un button, entonces tal vez también debería tener un estado hover ?

2022-08-29 19:51 UTC, JairDev commented
Porque en este pull request aparecen los commits de otra rama ?

2022-08-30 19:49 UTC, franmper requested changes
genial esto! te deje un par de comentarios nomas. Probablemente haya que revisar los diseños en figma para actualizarlo

2022-08-30 19:49 UTC, franmper commented on stories/Clip/Clip.tsx
> +      setTimeout(() => setClassNameValue("0"), 1000);
esto es para una animación? o para que sería?

2022-08-30 19:49 UTC, franmper commented on stories/Clip/Clip.tsx
> +      navigator.clipboard
podriamos chequear que ese navigator tiene el clipboard como propiedad? No estoy 100% seguro que en todos los navegadores funcione esto.

2022-08-30 19:49 UTC, franmper commented on stories/Clip/Clip.tsx
> +  const [messageContent, setMessageContent] = useState("Copiado");
Tendríamos que ver el diseño como queda por que este copiado se muestra siempre y solo deberia mostrarse cuando se copio el texto

2022-08-30 19:53 UTC, franmper commented
@JairDev otra cosa, guarda con no pasarse a master cuando inicias un nuevo componente, en este caso fijate que se te subieron un monton de cambio de las tabs. Para arreglarlo podes apuntar el pr a la rama de las tabs por ahora.

2022-08-30 20:14 UTC, JairDev commented on stories/Clip/Clip.tsx
> +      setTimeout(() => setClassNameValue("0"), 1000);
Para el mensaje de si fue exitoso o rechazado la acción de copiar el texto, este mensaje aparece debajo, y luego de "1s" desaparece, lo que estaban discutiendo ayer con el equipo de diseño, algo así tipo los mensajes en los formularios de si la contraseña es incorrecta, ese tipo de labels de error o éxito.

2022-08-30 20:15 UTC, JairDev commented on stories/Clip/Clip.tsx
> +      navigator.clipboard
Voy a chequearlo !

2022-08-30 20:20 UTC, JairDev commented on stories/Clip/Clip.tsx
> +  const [messageContent, setMessageContent] = useState("Copiado");
Ese mensaje es sobre el mensaje que me dejaste arriba osea está opacity 0 cuando se copia aparece y luego desaparece de nuevo, en mi máquina funciona jajajaj

2022-08-30 20:25 UTC, JairDev commented on stories/Clip/Clip.tsx
> +  const [messageContent, setMessageContent] = useState("Copiado");
Y claro sobre el diseño está el tema de mi primer comentario, si es un botón tal vez debería tener un estado hover !

2022-08-30 20:47 UTC, franmper commented on stories/Clip/Clip.tsx
> +      setTimeout(() => setClassNameValue("0"), 1000);
Podriamos hacer algo mas simple de entender como un booleano que se renderice o no de acuerdo a si se copio o no, o hubo error? Lo siento medio raro que se renderice un elemento en pantalla que no se muestre por que tiene opacidad 0.

2022-09-02 21:36 UTC, nykka requested changes
Genial!!! Te deje un comentario minimo

2022-09-02 21:36 UTC, nykka commented on stories/Clip/Clip.tsx
> +        title="copiar-texto"
A este boton le agregaria la propiedad `aria-labellledby` con el `id` del `span` (deberias agregarle un id`)` que contiene el mensaje de exito o error. De esta forma, el lector de pantallas va a anunciar ese mensaje.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby
https://www.awesomescreenshot.com/video/10866473?key=dcafed4dba5630361b7573d4fbe6b99d

2022-09-03 15:30 UTC, JairDev commented on stories/Clip/Clip.tsx
> +        title="copiar-texto"
Nykka utilizas alguna app para el screen reader ?

2022-09-06 20:13 UTC, nykka approved these changes
LGTM!!!

2022-09-07 16:56 UTC, merged