Feat/42 crear componente select
frontendcafe/water-call-for-papers pull request #115
Opened 2022-08-31 03:30 UTC by aledeloss

[Issue 42 - component Select](https://github.com/frontendcafe/water-call-for-papers/issues/42)

Se agrega la funcionalidad básica del componente, sin estilos ni storybook. Dejé algunos comentarios en el código de cosas que no me funcionan o creo que no están muy bien logradas. En particular:
- label, cómo dejarlo para el screen reader pero esconderlo cuando no hace falta que esté visible,
- la actualización del placeholder.
Estuve trabajando sobre la posibilidad de hacerlo múltiple, pero como me estaba llevando un rato y no estaba previsto en el issue original, lo dejé afuera. Si hace falta, puedo retomarlo, tengo las pruebas stasheadas.
No arranqué la story para no seguir dilatando el issue, podemos conversar si dejarlo para otro issue o seguirlo acá cuando esté ok el componente.

![imagen](https://user-images.githubusercontent.com/28830397/187586283-ed477d4a-5608-4631-baeb-e281ea7dfb79.png)
![imagen](https://user-images.githubusercontent.com/28830397/187586432-acb66888-8155-420e-b59f-25aaeafab919.png)

2022-08-31 03:32 UTC, aledeloss commented on stories/Select/Select.tsx
> +  value: string;
El value no lo estoy usando, vamos a necesitarlo?

2022-08-31 06:29 UTC, nicolashzmor commented on stories/Select/Select.tsx
> +        )}
Considerando que `<Listbox.Label>` lo vas a incorporar en ambos casos, se me ocurre que podrías hacer:
`<Listbox.Label aria-label={label}>{ isLabelVisible ? label : "" }</Listbox.Label>`

2022-08-31 06:33 UTC, nicolashzmor commented on stories/Select/Select.tsx
> +              {placeholder ?? selected.name}
El nullish coalescing operator (??) va a mostrar el `selected.name` sólo cuando placeholder tenga algún valor falsey (null, undefined, false, '', etc). Mientras `placeholder` tenga algún valor, `selected.name` no se va a mostrar.

2022-08-31 06:40 UTC, nicolashzmor commented on stories/Select/Select.tsx
> +  value: string;
En general la distinción de `name | value` se hace porque no en todos los casos vas a tener un nombre "human-readable".
Por ejemplo, si los códigos postales de una ciudad están distribuidos por barrio (aunque casi nunca es tan estricto), puede suceder que vos quieras mostrar en un select el nombre del barrio porque es mucho más facil para el usuario saber en qué barrio vive que cuál es su código postal, pero sin embargo, el dato que vos querés es el del código postal, no el nombre del barrio.
En ese caso, usarias `{ name: 'Las Golondrinas', value: '18180' }
Si se está haciendo un componente reutilizable, yo usaría `name + value`.

2022-08-31 11:56 UTC, TonyMckes commented on stories/Select/Select.tsx
> +        )}
Tambien podrias hacer algo como:

```suggestion
        <Listbox.Label className={isLabelVisible ? "" : "sr-only"}>
          {label}
        </Listbox.Label>
```
Tailwind tiene la clase `sr-only` para ocultar visualmente un elemento pero dejandolo en el DOM
More info: https://tailwindcss.com/docs/screen-readers

2022-08-31 12:06 UTC, TonyMckes commented on stories/Select/Select.tsx
> +              {/* Aquí se muestra siempre el placeholder (cuando hay) y no actualiza a los valores elegidos. :( */}
Se me ocurre que el placeholder puede ser el primer valor que se le pase a values... `values[0]`, y este venga `disabled`

Ejemplo:
```js
[
   { name: "Seleccione una opción --", isDisabled: true }
   { name: "Opcion 1", },
   { name: "Opcion 2", }
]
```

2022-09-01 20:31 UTC, aledeloss commented on stories/Select/Select.tsx
> +  value: string;
Entiendo, siempre mostramos el name. Pero yo debería hacer algo en mi componente para que luego cuando lo implementemos podamos tomar fácilmente el value asociado?

2022-09-01 20:32 UTC, aledeloss commented on stories/Select/Select.tsx
> +        )}
entiendo, gracias!!

2022-09-01 20:33 UTC, aledeloss commented on stories/Select/Select.tsx
> +        )}
Ahh, esto resuelve todo creo, gracias!

2022-09-01 20:33 UTC, aledeloss commented on stories/Select/Select.tsx
> +              {/* Aquí se muestra siempre el placeholder (cuando hay) y no actualiza a los valores elegidos. :( */}
Re, gracias!

2022-09-02 21:48 UTC, nykka requested changes
Esto esta muy bien Ale!!! Te dejé unos comentarios. Igual creo que falta aplicar los estilos, no?

2022-09-02 21:48 UTC, nykka commented on stories/Select/Select.tsx
> +        <div className="relative mt-1">
A este div le agregaria `aria-labelledby` con el `id` de un `div` o `span` que wrappee el mensaje de error. De esta forma va a ser anunciado por los lectores de pantalla. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby

2022-09-02 21:48 UTC, nykka commented on stories/Select/Select.tsx
> +      {errorMessage && <p>{errorMessage}</p>}
Aca estaria el `div` o `span` con el `id` para `aria-labelledby`

2022-09-02 21:48 UTC, nykka commented on stories/Select/Select.tsx
> +  const [selected, setSelected] = useState(renderValues[0]);
Faltaria que reciba un defaultValue para que ya tenga preseleccionado alguna opción que reciba por props

2022-09-02 22:11 UTC, aledeloss commented on stories/Select/Select.tsx
> +  const [selected, setSelected] = useState(renderValues[0]);
Yo pensé que el default value se pasa como isSelected: true en el array de values. Vos decís que se pase como otra prop? En tal caso, sacaría la opción de la `interface SelectValue,` pero sería más difícil de manipular cuando eventualmente hagamos de opción `multiple` por prop este componente.

2022-09-02 23:02 UTC, nykka commented on stories/Select/Select.tsx
> +      {errorMessage && <p>{errorMessage}</p>}
El id lo podes poner el el p

2022-09-06 20:25 UTC, merged