Actualizar componente Tag
frontendcafe/water-call-for-papers pull request #121
Opened 2022-09-01 19:04 UTC by bryanedward

https://github.com/frontendcafe/water-call-for-papers/issues/102

onClick se agrego y modificaciones del padding

Aquí si es necesario sumen imagenes o videos (pueden utilizar loom)

2022-09-01 19:47 UTC, franmper requested changes
Deje dos comentarios de cosas que se podrian simplicar mas, y solo revisa por que esta tirando error la story.

2022-09-01 19:47 UTC, franmper commented on stories/Tag/Tag.tsx
> +  color = "black",
el color yo lo dejaria que lo manden cuando se usan el componente, lo dejaria que la persona que lo utilice lo ponga y no sea limitado a los colores que le estas poniendo

2022-09-01 19:47 UTC, franmper commented on stories/Tag/Tag.tsx
> +  style = "primary",
lo mismo que habia puesto del color aplica a esto, en todo caso yo dejaria dos props:

```
backgroundColor: string,
textColor: string
```

que se pasen directo al classname para que se use desde la pagina que esta haciendo la persona que utilice las tags

2022-09-02 22:11 UTC, nykka requested changes
Va muy bien!!! Te dejo comentarios de unas cosas que habría que mejorar

2022-09-02 22:11 UTC, nykka commented on stories/Tag/Tag.tsx
> +  backgroundClassName?: string;
De ser posible tratemos de que no haya que pasar clases de tailwind para los colores de fondo o de texto. Lo mejor seria que reciba una prop con un nombre"amigable" y que el componente se encargue de renderizar los colores. Por ejemplo, si recibe status: "aprobada" entonces se renderiza con los colores rojos.
Por otro lado, quiza los styles primary y secondary no sean necesarios.

2022-09-02 22:11 UTC, nykka commented on stories/Tag/Tag.tsx
> +          <XMarkIcon size="small" theme="neutral" iconName="xmark" />
Como el contenido del boton es una imagen, hay que hacer ese icono no visible para los lectores de pantalla con `aria-hidden` y ademas agregar un label que solo sea visible para los lectores de pantalla que dice algo como "eliminar tag". Eso lo haces usando la clase sr-only de tailwind
https://tailwindcss.com/docs/screen-readers
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden

2022-09-05 14:26 UTC, franmper commented on stories/Tag/Tag.tsx
> +  backgroundClassName?: string;
esto se lo hice cambiar yo, mala mía, perdon @bryanedward

2022-09-05 23:55 UTC, franmper commented on stories/Spinner/CloseTag.tsx
> +  return (
por que esto es necesario? no se puede utilizar el componente icons?

2022-09-06 00:26 UTC, franmper approved these changes

2022-09-06 20:14 UTC, nykka approved these changes
LGTM!!!

2022-09-06 20:59 UTC, merged