DatePicker
frontendcafe/water-call-for-papers pull request #136
Opened 2022-09-09 15:53 UTC by ErikGIovani

https://github.com/frontendcafe/water-call-for-papers/issues/120

Componente Date Picker creado

2022-09-09 17:03 UTC, franmper requested changes
me parece que hay un error de estilos probablemente? 
![image](https://user-images.githubusercontent.com/38388588/189404161-1ea0787e-c477-46ab-b400-15f45c16e99a.png)


creo que actualizaron los estilos para el date picker

2022-09-09 17:25 UTC, franmper requested changes

2022-09-09 17:25 UTC, franmper commented on stories/DayPicker/DayPicker.tsx
> +          onChange={() => onChange}
esto puede ser directamente `onChange={onChange}`

2022-09-12 14:18 UTC, franmper requested changes
el resto creo que esta genial!

2022-09-12 14:18 UTC, franmper commented on stories/DayPicker/DayPicker.tsx
> +  onChange: () => void;
aca creo que esta mal el type 

![image](https://user-images.githubusercontent.com/38388588/189677615-479db1f4-d8bd-427e-9af8-9ce0c53694c1.png)

2022-09-12 22:13 UTC, nykka commented on styles/globals.css
> +
Quizá podemos probar esto? https://github.com/msnegurski/tailwind-react-datepicker/blob/master/styles/tailwind.css

2022-09-16 14:12 UTC, LPRegen commented on styles/globals.css
> +
Hola @nykka, acabo de aplicarlo.

2022-09-16 22:19 UTC, LPRegen commented on stories/DayPicker/DayPicker.tsx
> +  onChange: () => void;
Fran extendi la interfaz del comp como `HTMLInputElement`

2022-09-16 23:17 UTC, TonyMckes commented on stories/DayPicker/DayPicker.tsx
> +  onChange: () => void;
Lo entendiste mal Manu, el `onChange` es:

`onChange: (date: Date, event: SyntheticEvent<Event>) => void;`

2022-09-16 23:38 UTC, TonyMckes commented on stories/DayPicker/DayPicker.stories.tsx
> +import { DayPicker } from "./DayPicker";
```suggestion
import { ComponentStory, ComponentMeta } from "@storybook/react";
import { useState } from "react";
import { DayPicker } from "./DayPicker";
```

2022-09-16 23:38 UTC, TonyMckes commented on stories/DayPicker/DayPicker.stories.tsx
> +);
```suggestion
const Template: ComponentStory<typeof DayPicker> = (args) => {
  const [date, setDate] = useState<Date>(new Date());

  return <DayPicker {...args} date={date} onChange={setDate} />;
};
```

2022-09-16 23:39 UTC, TonyMckes commented on stories/DayPicker/DayPicker.stories.tsx
> +  date: new Date(),
```suggestion
```

2022-09-16 23:39 UTC, TonyMckes commented on stories/DayPicker/DayPicker.tsx
> +import { Icon } from "../Icon/Icon";
```suggestion
import es from "date-fns/locale/es";
import { SyntheticEvent } from "react";
import DatePicker, { registerLocale } from "react-datepicker";
import { Icon } from "../Icon/Icon";
registerLocale("es", es);
```

2022-09-16 23:40 UTC, TonyMckes commented on stories/DayPicker/DayPicker.tsx
> +  onChange: () => void;
```suggestion
  onChange: (date: Date, event: SyntheticEvent<Event>) => void;
```

2022-09-16 23:41 UTC, TonyMckes commented on stories/DayPicker/DayPicker.tsx
> +    "bg-white flex items-center gap-2 px-2 py-2 mt-1 text-sm border-2 rounded-md focus:border-2 focus:border-gray-400 disabled:border-gray-200";
```suggestion
    "bg-white flex items-center gap-2 px-2 py-2 mt-1 text-sm border-2 rounded-xl focus:border-2 focus:border-gray-400 disabled:border-gray-200";
```

2022-09-16 23:41 UTC, TonyMckes commented on stories/DayPicker/DayPicker.tsx
> +interface DatePickerProps extends HTMLInputElement {
```suggestion
interface DatePickerProps {
```

2022-09-16 23:45 UTC, TonyMckes requested changes
Hola @ErikGIovani! Te deje un par de suggestions (cosas minimas), de resto creo que estaria listo para merger!

2022-09-17 00:04 UTC, TonyMckes approved these changes
Ok, lo apruebo para que lo puedan usar en otros Issues

2022-09-19 19:15 UTC, merged