123 maquetar pantalla acerca de
frontendcafe/water-call-for-papers pull request #137
Opened 2022-09-10 16:03 UTC by JairDev

#123
La duda que tenía era sobre el tema de los iconos svg y renderizar diferentes iconos dependiendo de cada miembro, me pareció la manera mas limpia de hacerlo utilizando la librería iconify donde bueno, se puede utilizar un componente, el objeto de la data de los miembros es solo una referencia para explicar mi punto, que opinan ?

2022-09-12 14:29 UTC, franmper commented
@JairDev Te parece agregarle un width maximo de 1440px? por que en pantallas mas grandes que esa se ve muy raro las cards.

![image](https://user-images.githubusercontent.com/38388588/189680281-49b3409d-338c-4e0c-bac3-91cfeb3dfdc1.png)

El resto va muy genial!

2022-09-12 14:29 UTC, franmper commented
Otra cosa, creo que arrancaste tu rama desde la rama de Cards de tony, por lo que vas a tener que esperar que mergee el primero su rama.

2022-09-19 15:18 UTC, TonyMckes commented on pages/about-us.tsx
> +            <span className="text-blue-500">Frontend Café</span> desde el año
Hice click sobre el texto pensando que eran links jajaa
El azul no es parte del disenio pero me gusta la idea, quizas agregarle links no seria malo :smile:

2022-09-19 15:21 UTC, TonyMckes requested changes

2022-09-19 15:21 UTC, TonyMckes commented on pages/about-us.tsx
> +    <div className="p-6 md:p-10 max-w-[1440px]">
```suggestion
    <div className="p-6 md:p-10 max-w-[1440px] bg-white h-full">
```
Hola @JairDev! Se ve genial! Also, puedes actualizar tu rama para que tengas el sidebar y agregar el `padding` que faltaria para mobile

2022-09-30 19:45 UTC, nykka commented
Hola @JairDev veo que hay un montón de archivos. Son todos parte del PR? Si no es así, podrías indicarme cuales son los que debería mirar o hacer otro PR solo con los archivos que hiciste/cambiaste?

2022-10-03 18:06 UTC, JairDev commented on pages/about-us.tsx
> +            <span className="text-blue-500">Frontend Café</span> desde el año
Estaba en el diseño, por eso lo puse bro !

2022-10-11 19:31 UTC, JairDev commented
Hola @nykka lo que pasó aquí fue que acordamos crear un componente card en la misma carpeta que había creado tony, entonces me traje los cambios de esa rama, la de tony y cree el ContactTeamCard, para este issue mis cambios fueron crear ese componente, su historia en el mismo archivo de la storie de la Card de tony para reutlizar eso, y maquetar el about-us en pages !

2022-10-17 20:59 UTC, TonyMckes commented
Ok, esto se ve genial!. Solo faltaria solucionar lo de los archivos que estan demas

2022-10-18 16:55 UTC, TonyMckes commented
> Hola @nykka lo que pasó aquí fue que acordamos crear un componente card en la misma carpeta que había creado tony, entonces me traje los cambios de esa rama, la de tony y cree el ContactTeamCard, para este issue mis cambios fueron crear ese componente, su historia en el mismo archivo de la storie de la Card de tony para reutlizar eso, y maquetar el about-us en pages !

@nykka aca dejo los files linkeados

- [stories/Card/Card.stories.tsx](https://github.com/frontendcafe/water-call-for-papers/pull/137/files#diff-0d34e257a50eb2b438c0626cf17bc0e19646e18ea912e18edf6a684be2f27409)
- [stories/Card/ContactTeamCard.tsx](https://github.com/frontendcafe/water-call-for-papers/pull/137/files#diff-c2f064256466922492e771b43dcae0004236b8d72681daf5584848da0c6f4dc6)
- [pages/about-us.tsx](https://github.com/frontendcafe/water-call-for-papers/pull/137/files#diff-5334d371aed2a450a52623877484cdb9c0defde7d2900891687b03a644ae1fe0)

2022-10-18 20:53 UTC, nykka approved these changes
Perfecto! Lo unico que cambiaria es que los archivos dentro de la carpeta Card se llamen igual. Ej: TeamCard.tsx y TeamCard.stories.tsx

2022-10-18 22:03 UTC, TonyMckes approved these changes

2022-10-19 19:54 UTC, JairDev commented
Hola, decidí crear una carpeta para el componnente ContactTeamCard y su respectiva historia, me parece que queda mas organizado así.

2022-10-24 23:39 UTC, merged