Acordeon 1
frontendcafe/water-call-for-papers pull request #138
Opened 2022-09-11 15:23 UTC by ErikGIovani

https://github.com/frontendcafe/water-call-for-papers/issues/125

Acordeon 1 implementado

2022-09-12 14:27 UTC, franmper commented
@ErikGIovani Creo que te esta tirando un error de tipado en un handler. Por eso no puede deployar

![image](https://user-images.githubusercontent.com/38388588/189679835-66dde8c1-5725-4e39-a65a-d6b127b95fd9.png)

2022-09-12 15:18 UTC, franmper requested changes
te deje unos comentarios de las validaciones, yo dejaría solo las que son de numeros y letras, aunque creo que tambien se pueden manejar via props con el type

2022-09-12 15:18 UTC, franmper commented on stories/GeneratedData/GeneratedData.tsx
> +      } else if (e.target.value.length > 50) {
podriamos manejar esto via prop maxLength en el input y en el text area. Y agregarle un label de descripción/ayuda en cada uno

2022-09-12 15:18 UTC, franmper commented on stories/GeneratedData/GeneratedData.tsx
> +      if (e.target.value.length == 0) {
esto creo que tambien deberia manejarse via prop del input/textArea via el required

2022-09-12 15:18 UTC, franmper commented on stories/GeneratedData/GeneratedData.tsx
> +      if (e.target.value.length == 0) {
idem

2022-09-12 15:18 UTC, franmper commented on stories/GeneratedData/GeneratedData.tsx
> +      } else if (e.target.value.length > 50) {
idem

2022-09-12 15:18 UTC, franmper commented on stories/GeneratedData/GeneratedData.tsx
> +      if (e.target.value.length == 0) {
idem

2022-09-12 15:18 UTC, franmper commented on stories/GeneratedData/GeneratedData.tsx
> +      } else if (e.target.value.length > 280) {
idem

2022-09-12 15:18 UTC, franmper commented on stories/TextArea/TextArea.tsx
> +  onChange?: (e: ChangeEvent<HTMLTextAreaElement>) => void;
este se puede borrar despues que mergees main

2022-09-12 15:18 UTC, franmper commented on stories/TextArea/TextArea.tsx
> +        className={`px-2 py-2 mt-1 text-sm text-gray-700 border border-secondary-700 rounded-md placeholder:text-gray-300 focus:border-2 focus:border-primary-900 disabled:border-gray-300 active:borde
gracias por esto!

2022-09-12 15:19 UTC, franmper commented
una ultima cosa, podriamos dejar un todo en el input temas para cuando este mergeado cambiarlo por el componente correcto?

2022-09-12 21:50 UTC, franmper requested changes

2022-09-12 21:50 UTC, franmper commented on stories/GeneratedData/GeneratedData.tsx
> +      setData({ ...data, OrganizationName: e.target.value });
veo que hay bastante codigo repetitivo, podriamos hacer algo como?

```
if (["OrganizationName", "EventName", "Description"]. includes(e.currentTarget.name)) {
      setData({ ...data, OrganizationName: e.target.value });
      if (!validation) {
        setDataError({
          ...dataError,
          OrganizationName: "Este campo solo puede tener letras y numeros",
        });
      } else {
        setDataError({ ...dataError, OrganizationName: "" });
      }
}
```

2022-09-12 22:11 UTC, nykka requested changes

2022-09-12 22:11 UTC, nykka commented on stories/GeneratedData/GeneratedData.tsx
> +import { Disclosure } from "@headlessui/react";
Esto no deberia ser un componente, sino que deberías renderizar todo directamente en pages/event

2022-09-13 00:57 UTC, ErikGIovani commented on stories/GeneratedData/GeneratedData.tsx
> +import { Disclosure } from "@headlessui/react";
Creo que estaría mejor tener cada acordeón en un componente aparte y solo pasarle un estado, para obtener los datos de cada acordeón en un solo estado, así sería más modular y no tendríamos un componente tan complejo con toda la lógica para las validaciones, los estados y los inputs en un solo lugar 👌

2022-09-13 12:44 UTC, nykka commented on stories/GeneratedData/GeneratedData.tsx
> +import { Disclosure } from "@headlessui/react";
El tema es que la validación va a ser cuando la persona haga click en el boton de submit (y no en onChange como lo tenes ahora). Manejar la validación de cada _accordion_ de manera interna me parece poco práctico en ese sentido. Además que hay validaciones que se pueden compartir en varios inputs (sean de este _accordion_ o de otro).

2022-09-13 14:05 UTC, ErikGIovani commented on stories/GeneratedData/GeneratedData.tsx
> +import { Disclosure } from "@headlessui/react";
Y como se va a escribir en el input de tipo text si todos tienen un prop value en el value?

2022-09-19 15:38 UTC, TonyMckes commented on stories/GeneratedData/GeneratedData.tsx
> +import { Disclosure } from "@headlessui/react";
Se me ocurrio que se podria agregar la validacion de los tres acordeon `onSubmit` en otro issue, luego de que esten completados los tres en `/event/create.tsx`

2022-09-30 19:46 UTC, nykka requested changes

2022-09-30 19:46 UTC, nykka commented on stories/GeneratedData/GeneratedData.tsx
> +import { Disclosure } from "@headlessui/react";
@ErikGIovani vamos por ahora con lo que te comenté arriba:
Eliminá el componente GeneratedData y pasá todo al archivo create.tsx

2022-10-11 00:26 UTC, franmper approved these changes

2022-10-17 21:08 UTC, TonyMckes approved these changes

2022-10-17 21:08 UTC, TonyMckes commented on pages/event/create.tsx
> +            <Disclosure.Panel className="pt-2 pb-2 flex flex-col gap-2">
Cool! ya casi esta listo xP

Una cosa, puedes cambiar los componentes `Disclosure` por el `Accordion` que hizo Yolit?
Cualquier refactor de estilos se pueden agregar luego, para evitar confictos con otros branches

2022-10-17 22:49 UTC, nykka commented on pages/event/create.tsx
> +            <Disclosure.Panel className="pt-2 pb-2 flex flex-col gap-2">
Coincido con @TonyMckes !

2022-10-18 13:10 UTC, nykka approved these changes

2022-10-18 13:20 UTC, merged