139 maquetar lista de eventos
frontendcafe/water-call-for-papers pull request #141
Opened 2022-09-13 22:58 UTC by TonyMckes

Issue #139

Se agrego gran parte del layout para el listado de eventos. 

Falta agregar un par de componentes que estan en progreso/review. 
Y aparte algunas features quedaran desactivados por ahora,

2022-09-30 20:17 UTC, nykka requested changes
Esto esta quedando súper! Espero podamos avanzar pronto. Te dejé un par de comments 👯

2022-09-30 20:17 UTC, nykka commented on stories/StyledLink/StyledLink.tsx
> +        className={tw(
@TonyMckes habría que eliminar la función tx y renderizar el string de clases directamente

2022-09-30 20:17 UTC, nykka commented on pages/event/list.tsx
> +  useEffect(() => {
@TonyMckes No me queda claro para que estamos usando esto ahora. Es para usar queries en la URL, cierto? Si es así, creo que podemos usar `useRouter()` https://nextjs.org/docs/api-reference/next/router#userouter

2022-10-03 14:53 UTC, TonyMckes commented on stories/StyledLink/StyledLink.tsx
> +        className={tw(
Hola @nykka! Vale, estare atento para eliminarla antes de merguear

2022-10-03 14:57 UTC, TonyMckes commented on pages/event/list.tsx
> +  useEffect(() => {
No no, eso es para las queries que van al backend para los filtros y etc.

2022-10-19 21:52 UTC, franmper commented on pages/event/list.tsx
> +function FilterBar({ searchHandler, searchQuery }: FilterBarProps) {
podriamos mover esto a un componente? creo que en el futuro podria ser necesario en la lista de postulaciones

2022-10-19 22:13 UTC, TonyMckes commented on pages/event/list.tsx
> +function FilterBar({ searchHandler, searchQuery }: FilterBarProps) {
Sip, seguro!

2022-10-22 22:31 UTC, franmper approved these changes

2022-10-22 23:03 UTC, franmper approved these changes

2022-10-24 23:19 UTC, merged