create component filter
frontendcafe/water-call-for-papers pull request #142
Opened 2022-09-14 22:01 UTC by bryanedward

https://github.com/frontendcafe/water-call-for-papers/issues/73

creacion de un componente de filttro 

Aquí si es necesario sumen imagenes o videos (pueden utilizar loom)

2022-09-19 15:25 UTC, TonyMckes commented
He estado analizando este componente y note que sera un desafio agregarle accesibilidad :worried:
HeadlessUI (segun yo) como que no tiene una buena opcion para los tags

2022-09-19 16:51 UTC, bryanedward commented
@franmper  revisa porfa

2022-09-19 16:51 UTC, bryanedward commented
> He estado analizando este componente y note que sera un desafio agregarle accesibilidad 😟 HeadlessUI (segun yo) como que no tiene una buena opcion para los tags

exacto

2022-09-30 20:35 UTC, nykka requested changes
Va muy bien!!! Lo que si no es navegable usando el teclado y creo que necesita un poco de ajuste para que este como en los diseños:
<img width="219" alt="Screen Shot 2022-09-30 at 17 35 19" src="https://user-images.githubusercontent.com/8450941/193352349-0ea966b8-8775-4e1d-b81b-018798cfbcc1.png">

2022-09-30 20:35 UTC, nykka commented on stories/Filter/Filter.tsx
> +            <Menu.Button onClick={eventClick}>Filtro</Menu.Button>
En vez de tener una función aparte podes directamente hacer `onClick={() => inVisible(!visible)}`

2022-09-30 20:35 UTC, nykka commented on stories/Filter/Filter.tsx
> +  const clear = () => {};
Para que serían estas dos funciones?

2022-10-20 12:45 UTC, TonyMckes commented
Continuando el desarrollo de este componente, hice un refactor de toda la estructura del comp. Intentando mejorar la accesibilidad y agregando los estilos.

Tambien aproveche y hice refactor del componente `Radio` porque tenia un comportamiento extranio al hacer al navegarlo con el teclado

Ambos se deberian poder probar desde sus respectivas histories..

2022-10-22 18:58 UTC, franmper approved these changes

2022-10-22 18:58 UTC, merged