124 maquetar crear evento acordion 2
frontendcafe/water-call-for-papers pull request #144
Opened 2022-09-20 18:50 UTC by JairDev

#124 
Hola, bueno aquí faltan algunas cosas por hacer, hay unas inconsistencias en los diseños de los inputs, por ejemplo en el diseño tienen un padding top-bottom de 16px, el input text y el day picker tienen un padding de 8px, también el componente radio tiene un espacio por defecto que lo empuja a la derecha.
Sobre las validaciones en estos casos serían valores requeridos, pero estos componentes tienen valores por defecto, que debería validar ?
![acordeon2](https://user-images.githubusercontent.com/33360509/191339910-4185d658-c408-48a0-a02f-7bd066efb0e4.png)

2022-09-20 20:29 UTC, TonyMckes commented on pages/event/create.tsx
> +      <SidebarDrawer events={[]} />
El sidebar ya esta en agregado al `layout`, no necesitas agragarlo aca
Has merge de main para que tengas esos cambios

2022-09-20 21:40 UTC, TonyMckes commented on pages/event/create.tsx
> +  const [selected, setSelected] = useState<string>(options[0].title);
Sin estado inicial, aparece el placeholder.. En componente `Select` podrias exponer el `onChange` y `value`, asi sacamos el `state` y se maneja por fuera
```suggestion
  const [selected, setSelected] = useState<string>();
```

2022-09-20 21:41 UTC, TonyMckes commented on pages/event/create.tsx
> +  const [endDate, setEndDate] = useState<Date>(new Date());
```suggestion

  const [startDate, setStartDate] = useState<Date>();
  const [endDate, setEndDate] = useState<Date>();
```

2022-09-20 21:45 UTC, TonyMckes commented on pages/event/create.tsx
> +  const [endTime, setEndTime] = useState<string>(DATE);
```suggestion
  const [startTime, setStartTime] = useState<string>("00:00");
  const [endTime, setEndTime] = useState<string>("00:00");
```

2022-09-20 21:50 UTC, TonyMckes commented on pages/event/create.tsx
> +
El componente `Radio` necesitara su propio `state`
y puedes modificar la interface con
 
```ts
interface RadioGroup extends InputHTMLAttributes<HTMLInputElement> {
  // ...
  value: string | undefined;
  defaultValue?: string;
}
```
y lo dejarlo sin `defaultValue` para que inicie deselectionado, a la final creo que ayudara para las validaciones

2022-09-21 14:48 UTC, JairDev commented on pages/event/create.tsx
> +      <SidebarDrawer events={[]} />
Listo bro !

2022-09-21 15:55 UTC, JairDev commented on pages/event/create.tsx
> +  const [selected, setSelected] = useState<string>(options[0].title);
Bro no comprendo lo que me quieres decir aquí, cuando hablas de onChange y value te refires al componente Select o al componente Radio ?

2022-09-21 16:16 UTC, TonyMckes commented on pages/event/create.tsx
> +  const [selected, setSelected] = useState<string>(options[0].title);
En este comment me referia al componente Select, si

2022-09-30 20:54 UTC, nykka requested changes
@JairDev Va muy bien! Creo que es una buena oportunidad para ajustar componentes que ya estaban, algunos ejemplos: 
- Los inputs no tienen todos el mismo alto
- Cuando abris el select, los iconos de otros inputs se siguen viendo:
<img width="880" alt="Screen Shot 2022-09-30 at 17 42 46" src="https://user-images.githubusercontent.com/8450941/193354384-f8591625-65aa-4199-9e29-1cfb684b366c.png">
- Esta parte se ve rara, le preguntaria al equipo de diseño como se debería ver:
<img width="345" alt="Screen Shot 2022-09-30 at 17 52 43" src="https://user-images.githubusercontent.com/8450941/193354574-6cdfc7e2-1fb3-4275-8568-530688300bb7.png">

2022-10-11 00:35 UTC, franmper commented
> @JairDev Va muy bien! Creo que es una buena oportunidad para ajustar componentes que ya estaban, algunos ejemplos:
> 
> * Los inputs no tienen todos el mismo alto
> * Cuando abris el select, los iconos de otros inputs se siguen viendo:
> 
> <img alt="Screen Shot 2022-09-30 at 17 42 46" width="880" src="https://user-images.githubusercontent.com/8450941/193354384-f8591625-65aa-4199-9e29-1cfb684b366c.png">
> 
> - Esta parte se ve rara, le preguntaria al equipo de diseño como se debería ver:
> <img alt="Screen Shot 2022-09-30 at 17 52 43" width="345" src="https://user-images.githubusercontent.com/8450941/193354574-6cdfc7e2-1fb3-4275-8568-530688300bb7.png">

Tiene diseño esa parte, deberia estar contra el lado izquierdo

2022-10-17 20:28 UTC, TonyMckes commented on pages/event/create.tsx
> +      <SidebarDrawer events={[]} />
@JairDev te falta hacer merge de `main` para que puedas sacar el sidebar

2022-10-17 20:43 UTC, TonyMckes requested changes
esta quedando genial, definitivamente esta mas completo, solo un par de cositas que te deje

2022-10-17 20:43 UTC, TonyMckes commented on pages/event/create.tsx
> +                    value=""
Faltaria habilitar este input, si quieres lo puedes hacer o si no, sugiero agregar un commentario `//TODO: ` para agregarlo a un issue aparte y asi hacer nuevos "micro issues"

2022-10-18 15:59 UTC, JairDev commented
Los archivos a revisar, el pages/event/create, TimePicker, y los refactor de Select y DayPicker

2022-10-18 20:48 UTC, nykka reviewed
@JairDev Te dejé algunos comentarios!

2022-10-18 20:48 UTC, nykka commented on stories/TimePicker/TimePicker.tsx
> +import React from "react";
Hay alguna razón por la cual este componente no tiene un archivo stories?

2022-10-18 21:01 UTC, JairDev commented on stories/TimePicker/TimePicker.tsx
> +import React from "react";
Voy a hacer el storie para ese componente

2022-10-19 21:56 UTC, franmper commented on pages/event/create.tsx
> +    // console.log("submit");
podriamos eliminar este console log, verdad? Tambien deberiamos dejar un todo para refactorizar esta funcion, por que creo que se puede achicar un monton. Por otro lado, me parece que el `e.preventDefault()` deberia ir al inicio

2022-10-20 21:15 UTC, JairDev commented
Team, sobre el input de localización se refiere a " Av. X, calle 2222" ?  y sobre esta función checkInputValue esta bien llamar al setValue de esa manera me refiero sin un  return setValue, typescript no me dio error, pero que me dicen ustedes ?

2022-10-20 21:36 UTC, franmper commented on lib/utils.ts
> +    setValue(false);
creo que podriamos hacer directamente `setValue(Boolean(value))`

2022-10-20 21:40 UTC, franmper commented on lib/utils.ts
> +    setValue(false);
>  sobre esta función checkInputValue esta bien llamar al setValue de esa manera me refiero sin un return setValue, typescript no me dio error, pero que me dicen ustedes ?

mmm no estoy seguro si el return hara diferencia en este caso sinceramente. Yo se lo pondria pero mas por costumbre que por otra cosa.

2022-10-20 21:44 UTC, franmper commented
@JairDev tiene varios conflictos el pr, yo los iria resolviendo, por que mientras mas se acumulando mucho mas dificil es resolverlos 🙂

2022-10-22 18:45 UTC, JairDev commented
El input location no le he trabajado, por las inconsistencias que hay en las validaciones, en los otros inputs se está haciendo onchange, entonces los inputs de texto y número se validan onchange y los otros tipo date o time onsubmit ?

2022-10-22 19:00 UTC, JairDev commented
esto  setValue(Boolean(value)) lo dejé con el if else, por tema de legibilidad, no te parece que es mas legible ?

2022-10-22 19:59 UTC, franmper commented
> esto setValue(Boolean(value)) lo dejé con el if else, por tema de legibilidad, no te parece que es mas legible ?

genial!

2022-10-24 22:58 UTC, merged