126 maquetar crear evento accordion 3
frontendcafe/water-call-for-papers pull request #145
Opened 2022-10-14 12:36 UTC by LPRegen

### Issue link

[Maquetar Crear evento acordion 3 #126](https://github.com/frontendcafe/water-call-for-papers/issues/126)

### Descripcion:

Se crea componente Accordion 3.

#### Modificaciones a comp. existentes:
- TextArea, reemplazo de color de texto en placeholder.
- DayPicker:
    - `untilDays`(number): default es `90`. Especifica rango de cuantos dias hacia el futuro deberian estar habilitados para seleccionar por el usuario.
    - `includeDateIntervals`: incluye fechas posibles para que sean seleccionadas por el usuario en un rango especifico. (Docs includeDateIntervals)[https://reactdatepicker.com/#example-include-date-intervals]

2022-10-17 14:29 UTC, TonyMckes requested changes
@LPRegen creo que estas haciendo cambios sobre un branch desactualizado.
Y el acordion va directamente en `pages/event/create.tsx`, no hace falta historia de storybook

> Also, seguro encontraras cosas por refactorizar, intenta dejarlos para luego y asi abrir nuevos issues especificamente para eso

2022-10-19 08:33 UTC, LPRegen commented on pages/event/create.tsx
> +    <form className="grid gap-14 mx-auto w-full lg:max-w-xl bg-white">
Agregue el gap entre los elementos.

2022-10-19 08:34 UTC, LPRegen commented on pages/event/create.tsx
> -              <InputText
Desde esta linea hasta la linea numero 122 simplemente es el formateo de la indentacion.

2022-10-19 08:35 UTC, LPRegen commented on pages/event/create.tsx
> +  const handleDateChange = (date: Date, toModify: string) => {
Validacion de fechas seleccionadas por el usuario.

2022-10-19 08:35 UTC, LPRegen commented on pages/event/create.tsx
> +      ["OrganizationName", "EventName", "Description", "Requirements"].includes(
Agregue el item `Requirements` para realizar la validacion.

2022-10-19 08:40 UTC, LPRegen commented
Ahora segun lo que converse con @TonyMckes , el file Accordion-3.tsx debo eliminarlo verdad? De ser asi lo elimino junto a su story.

2022-10-19 11:33 UTC, TonyMckes commented on pages/event/create.tsx
> +import isEqual from "date-fns/isEqual";
Hmm... Esta lib ya esta instalada?
Pregunto porque no veo el `package.json` listado con cambios

2022-10-19 11:38 UTC, LPRegen commented on pages/event/create.tsx
> +import isEqual from "date-fns/isEqual";
Hola Tony, resulta que viene instalada con la libreria `react-datepicker`

https://reactdatepicker.com/

2022-10-19 20:06 UTC, nykka approved these changes
Genial!!!

2022-10-19 20:31 UTC, TonyMckes approved these changes

2022-10-20 03:24 UTC, merged