Feat/crear component input text
frontendcafe/water-call-for-papers pull request #27
Opened 2022-08-11 16:45 UTC by yolitzr

Issue [#10 ](https://github.com/frontendcafe/water-call-for-papers/issues/10)

Esta la mayoría de los input descritos en la issue, y se agrego un texto faltante para campo requerido . Queda pendiente definir estados focus y active porque creo que iría más por color.

2022-08-11 17:56 UTC, TonyMckes commented on stories/Input/InputText.tsx
> +      {visible && (
El label no deberia ser opcional, en lugar de removerlo del DOM agrega algun estilo (`hidden` o `invisible`).
Tambien podrias agregar un atributo `htmlFor` para "asociar" el label con el input (el input necesitaria un `id`), o opcionalmente envuelves el input dentro del label

2022-08-11 17:58 UTC, TonyMckes commented on stories/Input/InputText.tsx
> +      <p className="text-xs leading-6 text-gray-400">{description}</p>
Aca si vendria bien el short circuit `{description && <p></P>`

2022-08-11 18:11 UTC, yolitzr commented on stories/Input/InputText.tsx
> +      {visible && (
Vale, ahi cambio el estilo y encierro mejor el input en el label. Gracias!!

2022-08-11 18:11 UTC, yolitzr commented on stories/Input/InputText.tsx
> +      <p className="text-xs leading-6 text-gray-400">{description}</p>
Listo!!

2022-08-11 18:59 UTC, TonyMckes approved these changes
Perfect!

2022-08-12 20:20 UTC, nykka requested changes
Muy bueno!!! 🎉 
Deje varios comentarios para mejorar cositas!

2022-08-12 20:20 UTC, nykka commented on stories/Input/InputText.tsx
> +  label: string;
No te olvides de poner un comment por cada prop explicando para que esta.

2022-08-12 20:20 UTC, nykka commented on stories/Input/InputText.tsx
> +}
Aca quiza puedas extender la interfaz con HTMLInputElement
https://bobbyhadz.com/blog/typescript-extend-type
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement

2022-08-12 20:20 UTC, nykka commented on stories/Input/InputText.tsx
> +  icon?: React.ReactNode;
Esto quiza lo tengamos que revisitar ya que vamos a tener componentes para cada icono

2022-08-12 20:20 UTC, nykka commented on stories/Input/InputText.tsx
> +  position?: string; // To position Icon to the right or left of the input
Aca seria mejor limitar el value a “left” o “right” en vez de que sea un string

2022-08-12 20:20 UTC, nykka commented on stories/Input/InputText.tsx
> +  const positionIcon = position == "left" ? `left-6` : `right-6`;
En vez de hacer este ternario, podes hacer `${position}-6`

2022-08-12 20:20 UTC, nykka commented on stories/Input/InputText.tsx
> +  const withDisabled = disabled && "disabled:border-gray-200";
No es necesario hacer este chequeo, tailwind va a aplicar estos estilos (diabled:border-gray-200) solo si el input esta disabled.

2022-08-12 20:20 UTC, nykka commented on stories/Input/InputText.tsx
> +            <path d={pathIcon}></path>
Creo que es muy complejo pasar el path del svg como prop. Aca quiza podamos hacer algo con los componentes de iconos.

2022-08-12 20:20 UTC, nykka commented on stories/Input/InputText.tsx
> +      {(error && <p className="mt-2 text-xs text-red-500">{error}</p>) ||
Aca no es necesario el OR, si hay error, renderiza el parrafo del error. Por otro lado, si es requerido, entonces renderiza el parrafo de que es required.

2022-08-12 20:20 UTC, nykka commented on stories/Input/InputText.tsx
> +          visible ? "block" : "hidden"
el tag label siempre se deberia renderizar, lo que puede que este o no este es {label}.
Ahi podrias hacer un ternario y si es visible entonces se renderiza normalmente… si no es visible, se renderiza como visually hidden o screen reader only.
https://tailwindcss.com/docs/screen-readers

2022-08-16 15:15 UTC, yolitzr commented on stories/Input/InputText.tsx
> +          visible ? "block" : "hidden"
Hice el ternario igual en el tag, pero en vez de block o hidden, agregar el screen reader, se redenriza igual el tag,.

Con label 
![imagen](https://user-images.githubusercontent.com/64231666/184915796-c14a4d42-4a7d-4d24-af22-ed6a8ecfb24d.png)

Sin label 
![imagen](https://user-images.githubusercontent.com/64231666/184915862-b786bc0b-4a3a-48e3-b748-82247496fdc8.png)

2022-08-19 22:41 UTC, nykka approved these changes
Genial! Vamos a mergearlo y voy a crear una tarea para agregarle el ícono!

2022-08-19 23:07 UTC, merged