Feat/crear componente tag
frontendcafe/water-call-for-papers pull request #34
Opened 2022-08-11 21:04 UTC by JairDev

Issue #11 

Se crearon varios casos(historias) para el componente Tag, como estilo primario, secundario, medidas sm, md, lg, estas medidas las trabajé solo cambiando el tamaño de la fuente y un mismo padding para todos, también se creó un componente TagList para renderizar multiples componentes Tag y ver como se comportaba la UI.

2022-08-11 22:19 UTC, TonyMckes commented on stories/Tag/Tag.tsx
> +  style: string;
Si agregas Union Types `style: primary | secondary | example;` TypeScript sera mas estricto usar esas props y Storybook tambien sera mas amigable, lo mismo para `size`

2022-08-11 22:22 UTC, TonyMckes commented on stories/Tag/Tag.tsx
> +      className={`${primaryStyle} ${secondaryStyle} ${smallSize} ${mediumSize} ${largeSize} ${hidden} p-1.5 rounded-full text-center`}
Si puedes hacer que el `div` no ocupe todo el ancho de su container seria genial! Asi los Tags seran del tamaño del texto

2022-08-12 19:48 UTC, JairDev commented on stories/Tag/Tag.tsx
> +  style: string;
Hola Tony, ya agregue estos cambios, hasta que punto es bueno ser lo mas estricto con typescript ?

2022-08-12 19:49 UTC, JairDev commented on stories/Tag/Tag.tsx
> +      className={`${primaryStyle} ${secondaryStyle} ${smallSize} ${mediumSize} ${largeSize} ${hidden} p-1.5 rounded-full text-center`}
Agregué un ancho máximo y corregí el padding, gracias por tu observación !

2022-08-12 20:03 UTC, nykka requested changes
Esta genial!!! 🎉 
Solo algunos comentarios para simplificar los estilos!

2022-08-12 20:03 UTC, nykka commented on stories/Tag/Tag.tsx
> +  const primaryStyle = props.style === "primary" ? "bg-blue-400" : "";
Quiza podrias hacer un diccionario, algo asi:
```
const styleList = {
 primary: “bg-blue-400”,
 secondary: “bg-emerald-400”,
}
```
y despues, accedes haciendo styleList[style]
Lo mismo con el size!

2022-08-12 20:19 UTC, JairDev commented on stories/Tag/Tag.tsx
> +  hidden?: boolean;
Hola nykka, en el issue Label (requerido): visible u oculto, créeme que estaba pensando a que se refiere ese visible u oculto ?

2022-08-13 13:59 UTC, TonyMckes commented on stories/Tag/Tag.tsx
> +  style: string;
Hola! La verdad no se mucho de TypeScript, pero se que si por ejemplo eres especifico con los `styles` y etc... el editor de codigo nos "gritara" si intentamos usar un valor que tu componente no permita

2022-08-13 14:04 UTC, TonyMckes commented on stories/TagList/TagList.tsx
> +    <div className="grid gap-4 grid-cols-3">
Fijate que tal se ve con `flex gap-4`

2022-08-13 14:20 UTC, TonyMckes commented on stories/Tag/Tag.stories.tsx
> +  style: "secondary",
Veo que se estas repitiendo el `style: secondary,` en la mayoria de las historias, justo aprendi que se puede hacer de esta forma:
```js
export default {
  title: "Example/Tag", // Title for our storybook
  component: Tag, // Component to render

  args: {  // You can provide a 'default' to all the histories!
    style: "secondary", // With this you won't need to write it in every each one of them
  },
} as ComponentMeta<typeof Tag>;
```
esto
https://storybook.js.org/docs/react/writing-stories/args#component-args

2022-08-15 22:36 UTC, nykka commented on stories/Tag/Tag.stories.tsx
> +  style: "secondary",
Muy bueno!

2022-08-15 22:40 UTC, nykka requested changes
Esto ya esta casi listo!!! 🎉

2022-08-15 22:40 UTC, nykka commented on stories/Tag/Tag.tsx
> +      <label>{label}</label>
En vez de usar un label, usaria un span o un p. 
> El Elemento HTML <label> representa una etiqueta para un elemento en una interfaz de usuario
En este caso no está representando ningun elemento, así que no corresponde.

2022-08-15 22:40 UTC, nykka commented on stories/Tag/Tag.tsx
> +      className={`${styleColorClass} ${styleSizeClass} py-1.5 px-8 rounded-full text-center max-w-max`}
Acá podes pasar directamente styleList[style] y styleList[size], y nos ahorramos las lineas 16 y 17 :)

2022-08-16 19:26 UTC, nykka approved these changes
🎉 LGTM!

2022-08-16 23:16 UTC, merged