14 investigar sobre el input tipo file
frontendcafe/water-call-for-papers pull request #36
Opened 2022-08-11 23:06 UTC by ErikGIovani

[Investigar sobre el input tipo file](https://github.com/frontendcafe/water-call-for-papers/tree/14-investigar-sobre-el-input-tipo-file)

Objeto de configuración del addon-postcss agregado para reparar el warning y se movió la dependencia a las dependencias de desarrollo como lo indica la documentación, también se agregó la accesibilidad al custom input para habilitar el acceso por el teclado al input, estoy a la espera de los requerimientos del input 👌.

2022-08-12 20:08 UTC, nykka requested changes
Buen laburo! 🎉  Aunque la idea de esta tarea era solo de investigacion para poder definir entre todes que camino seguir, me gustaria poder ver como funciona y se navega con teclado o screen reader. Cuando este en casa lo miro corriendo storybook.

2022-08-12 20:08 UTC, nykka commented on stories/InputFile/InputFile.tsx
> +  label: string;
Recorda agregar un comment con la descripcion de cada uno!

2022-08-12 20:08 UTC, nykka commented on stories/InputFile/InputFile.tsx
> +        tabIndex={tabIndex}
Ojo que agregar tab index no es recomendado en terminos de accesibilidad. Cual es su funcion aca?

2022-08-12 20:09 UTC, nykka commented on stories/InputFile/InputFile.tsx
> +}
Aca quiza podamos extender la interface con los types de HTMLInputElement
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement
https://bobbyhadz.com/blog/typescript-extend-type

2022-08-12 20:14 UTC, ErikGIovani commented on stories/InputFile/InputFile.tsx
> +        tabIndex={tabIndex}
El tabindex se usa en accesibilidad cuando son componentes custom que se quieren que sean accesibles desde la navegación con el teclado, en este caso el componente custom no es accesible con el tab del teclado y con el tabindex se hace accesible con el tab 👌

2022-08-12 20:19 UTC, ErikGIovani commented on stories/InputFile/InputFile.tsx
> +}
Leí la documentación y todo lo que encuentre, probé con el KeyboardEvent, el React.Event, SyntheticEvent y uno hacía que el otro marcara error, aparecía en los eventos del teclado no existe click, o que no existía target y si lo hacia de tipo click decía que no existían los eventos del teclado

2022-08-12 20:32 UTC, ErikGIovani commented on stories/InputFile/InputFile.tsx
> +  label: string;
Gracias por el feedback ❤

2022-08-13 14:40 UTC, TonyMckes commented on stories/InputFile/InputFile.tsx
> +}
Prueba con `InputHTMLAttributes<HTMLButtonElement>`, asi corregi el boton aunque no se si lo hice de forma correcta, pero esta genial eso

```ts 
interface InputFileProps extends InputHTMLAttributes<HTMLButtonElement> {
  // ...
}
```

2022-08-15 22:19 UTC, nykka commented on stories/InputFile/InputFile.tsx
> +        tabIndex={tabIndex}
Se para que se usa el tab index, pero siempre es preferibla no usarlo si se puede resolver de otra manera.

2022-08-15 22:32 UTC, nykka requested changes
Vamos avanzando! Te dejé algunos comentarios más.
Fijate esta implementación que me parece que nos puede servir si la adaptamos a los wireframes: https://flowbite.com/docs/forms/file-input/#dropzone

2022-08-15 22:32 UTC, nykka commented on stories/InputFile/InputFile.tsx
> +      <label
Ojo! Hay que asociar un solo label a un solo elemento

2022-08-15 22:32 UTC, nykka commented on stories/InputFile/InputFile.tsx
> +        {label}
Este label deberiamos hacer que sea optativo que se vea, aunque si tenemos que dejarlo visible para lectores de pantalla https://tailwindcss.com/docs/screen-readers#screen-reader-only-elements

2022-08-15 22:32 UTC, nykka commented on stories/InputFile/InputFile.tsx
> +      <p className="font-normal text-xs text-gray-600">1500 x 600. Max. 5MB</p>
Esto deberia tambien ser opcional y el texto pasarse por props.

2022-08-15 22:32 UTC, nykka commented on utils/ShiftBy.tsx
> +interface ShiftByProps {
En esta instancia no tenemos que ser tan precisos con como se ve ya que no tenemos diseño. Por ahora eliminemos este archivo :)

2022-08-16 21:23 UTC, nykka commented on stories/InputFile/InputFile.tsx
> +        onKeyDown={(e: any) => e.key === "Enter" && e.target.click()}
Acá podes usar https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event

2022-08-16 21:24 UTC, nykka commented on stories/InputFile/InputFile.tsx
> +        <ShiftBy y={-2}>{placeholder}</ShiftBy>
Acordate de borrar ShiftBy y renderizar {placeholder} directamente

2022-08-16 21:25 UTC, nykka commented on stories/InputFile/InputFile.tsx
> +          xmlns="http://www.w3.org/2000/svg"
Aca habria que agregar un aria-hidden ya que es un elemento decorativo y lo queremos ocultar de los lectores de pantalla

2022-08-17 21:29 UTC, nykka approved these changes
Muy buen laburo! 💯

2022-08-18 01:34 UTC, merged