Add/events
frontendcafe/water-call-for-papers pull request #38
Opened 2022-08-12 22:11 UTC by bryanedward

Aquí va el link del issue

Esta es una descripción de prueba

Aquí si es necesario sumen imagenes o videos (pueden utilizar loom)

2022-08-12 23:43 UTC, TonyMckes commented
Algo raro paso con el `package-lock.json`, que piensas que pudo haber pasado @franmper?

2022-08-16 00:26 UTC, franmper commented
> Algo raro paso con el `package-lock.json`, que piensas que pudo haber pasado @franmper?

Por que raro? Por que no se ve el diff? Probablemente al instalar alguna version diferente de las librerias paso esto de que el diff sea muy grande. Normalmente el lock no es tan importante, ya que puede llegar a variar.

2022-08-16 01:02 UTC, TonyMckes commented
> > Algo raro paso con el `package-lock.json`, que piensas que pudo haber pasado @franmper?
> 
> Por que raro? Por que no se ve el diff? Probablemente al instalar alguna version diferente de las librerias paso esto de que el diff sea muy grande. Normalmente el lock no es tan importante, ya que puede llegar a variar.

Me llamo la atencion que dice `129 additions, 23,620 deletions not shown because the diff is too large...`, pero si no pasa nada todo bien!

2022-08-16 13:18 UTC, franmper commented
> > > Algo raro paso con el `package-lock.json`, que piensas que pudo haber pasado @franmper?
> > 
> > 
> > Por que raro? Por que no se ve el diff? Probablemente al instalar alguna version diferente de las librerias paso esto de que el diff sea muy grande. Normalmente el lock no es tan importante, ya que puede llegar a variar.
> 
> Me llamo la atencion que dice `129 additions, 23,620 deletions not shown because the diff is too large...`, pero si no pasa nada todo bien!

probablemente hubo algun cambio de version de alguna libreria (normalmente esto conlleva un cambio en otras dependencias internas de esa libreria y asi, por eso tantas lineas), seria bueno no subirlo en general, pero no es grave

2022-08-16 17:34 UTC, franmper requested changes
Genial esto!! Deje unos comentarios menores, gracias!

2022-08-16 17:34 UTC, franmper commented on lib/utils.ts
> +export const timestamp = (date: any): Date => {
podriamos cambiarle a un nombre mas descriptivo de lo que hace? capaz agregarle un comentario de que hace tambien. Algo como `formatFirebaseDate` o algo asi?

2022-08-16 17:34 UTC, franmper commented on pages/api/events/index.ts
> +      break;
aca deberia responder algo igualmente. Por ejemplo `res.status(500).send("Method not allowed")`?

2022-08-16 17:34 UTC, franmper commented on pages/api/events/index.ts
> +          message: "disconnect db",
no necesariamente el error va a ser por que se desconecto de la base de datos, podria ser un error interno de la funcion. Capaz dejarlo por ahora con un mensaje mas generico?

2022-08-16 17:34 UTC, franmper commented on pages/api/organizers/index.ts
> +    case "GET":
Este endpoint entiendo que no es necesario, ya que en ningún momento en el front necesitaran el listado de todos los organizadores

2022-08-16 17:34 UTC, franmper commented on services/organizers.ts
> +  const querySnathop = await getDocs(
`querySnapshot`

2022-08-16 17:34 UTC, franmper commented on services/events.ts
> +  for (let index = 0; index < querySnathop.docs.length; index++) {
creo que seria mejor hacer un map en vez de un for clasico.

2022-08-17 16:47 UTC, bryanedward commented
realize los cambios @franmper

2022-08-17 23:44 UTC, franmper approved these changes

2022-08-17 23:47 UTC, merged