Crear componente Icons
frontendcafe/water-call-for-papers pull request #53
Opened 2022-08-16 22:40 UTC by Fedef11980

Aquí va el link del issue

Esta es una descripción de prueba

Aquí si es necesario sumen imagenes o videos (pueden utilizar loom)

2022-08-16 22:42 UTC, nykka commented on package.json
> +    "lint": "eslint --ignore-path .gitignore \"**/*.{jsx,js,tsx,ts}\"",
Por que tuviste que hacer este cambio?

2022-08-16 22:42 UTC, Fedef11980 commented on package.json
> +    "lint": "eslint --ignore-path .gitignore \"**/*.{jsx,js,tsx,ts}\"",
Da un error en windows y de esta forma se solucionó

2022-08-23 15:02 UTC, nykka requested changes
Muy bueno Fede!!! 🎉 
Lo único que revisaría es como va a usarse este componente en las vistas que tenemos que armar. Me parece poco practico tener que pasar las clases de tailwind por props, en vez de eso se puede definir tamaños (small, medium, large) y que al pasar uno de esos valores por props, se renderizen las clases de tailwind que los muestran de ese tamaño. 
Lo mismo con el nombre, habria que saber los nombres de cada icono de la libreria para poder pasarlo por props. En vez de eso se podria o definir valores mas "amigables" (ej iconName: "menu" y que eso renderize menu-alt-2) o componentes separados para cada icono (ej. <MenuIcon />, <SearchIcon />, etc). 
Otra cosa que hay que tomar en cuenta es color, hay situaciones donde el icono va a estar sobre un fondo claro, oscuro o gris y eso si deberiamos poder manejarlo via props, pasando un color o un theme:

<img width="395" alt="Screen Shot 2022-08-23 at 11 57 02" src="https://user-images.githubusercontent.com/8450941/186191790-d46a9fbf-94e7-45b6-a71a-a8a3a7bb5bd8.png">

<img width="230" alt="Screen Shot 2022-08-23 at 11 54 50" src="https://user-images.githubusercontent.com/8450941/186191800-6636ce73-2f30-4862-8a20-9e58db6fa3e2.png">

Yo creo que el resultado final óptimo podria ser que, al usar el componente, tenga que escribir alguna de estas dos opciones:

`<MenuIcon theme="light" /> ` o  `<Icon name="menu" theme="light" /> `

Me inclino mas a la primera, pero puede ser cualquiera de las dos.

2022-08-26 14:09 UTC, nykka requested changes
Esto ya esta casi casi listo! Acordate de usar nombres mas amigables para los iconos, te dejé algunos ejemplos. Y por ultimo cambiar el tipo de IconName de string a la lista final de nombres posibles

2022-08-26 14:09 UTC, nykka commented on stories/Icons/Icons.tsx
> +/* const iconName: Record<string, string> = {
Esto si no va a ir, hay que borrarlo

2022-08-26 14:09 UTC, nykka commented on stories/Icons/Icons.tsx
> +  "documentArrowDown":<DocumentArrowDownIcon/>,
"download"

2022-08-26 14:09 UTC, nykka commented on stories/Icons/Icons.tsx
> +  "documentPlus":<DocumentPlusIcon/>,
"add-doc"

2022-08-26 14:09 UTC, nykka commented on stories/Icons/Icons.tsx
> +  "documentMinus":<DocumentMinusIcon/>,
"remove-doc"

2022-08-26 14:09 UTC, nykka commented on stories/Icons/Icons.tsx
> +
Deberiamos borrar estas lineas vacias

2022-08-26 14:09 UTC, nykka commented on stories/Icons/Icons.tsx
> +  "share-compartir": <ShareIcon />,
"share"

2022-08-26 15:13 UTC, nykka commented
Hay un par de iconos que no se ven, aca te dejo unos ejemplos
<img width="1440" alt="Screen Shot 2022-08-26 at 12 11 37" src="https://user-images.githubusercontent.com/8450941/186936975-ef120389-9887-499e-8019-9851310b2a49.png">
<img width="1440" alt="Screen Shot 2022-08-26 at 12 11 29" src="https://user-images.githubusercontent.com/8450941/186936992-948cce74-68cd-4500-baf3-582e5cf5dfd2.png">

2022-09-01 19:33 UTC, merged