Feat/crear componente tabs
frontendcafe/water-call-for-papers pull request #75
Opened 2022-08-19 18:09 UTC by JairDev

Issue #41

Con este componente(el de headlessui) me enrede un poco por el tema de probar de forma aislada los diferentes estados en storybook, así que me pareció mas fácil testear un simple button y ver los diferentes estilos de acuerdo a los props ya que sobre el tema de la accesibilidad, la librería headlessui lo facilita, sobre los props, por ejemplo: el estado selected, la librería lo maneja mediante render props, el componente principal no recibe un props para diferentes estados, espero haberme explicado, que opinan ?

2022-08-19 22:20 UTC, nykka requested changes
Va muy bien!!! Te deje un par de comentarios. Estaria bueno juntarnos para ver como podemos mejorarlo 👯

2022-08-19 22:37 UTC, JairDev commented on stories/ButtonTabs/ButtonTabs.tsx
> +const buttonTabsStyles = {
El estado de noSelected, es cuando una tabs no está seleccionada valga la redundancia, me refiero a cuando una tab está seleccionada, noSelected es el estado de las otras, pasé los estados hover, focus, etc, como props para crear las diferentes historias y probar de manera aislada el ui, si los tuviera en las clases todas las historias tendría hover y focus, fijate que creé historias separadas para focus y hover !

2022-08-19 22:39 UTC, JairDev commented on stories/Tabs/Tabs.tsx
> +  const [events] = useState([
De acuerdo, solo es un componente de presentación !

2022-08-19 22:41 UTC, JairDev commented on stories/ButtonTabs/ButtonTabs.tsx
> +export const ButtonTabs = ({ states = "active" }: ButtonTabsProps) => {
Por lo que comenté en mi primer comentario del PR, se me hizo mas sencillo probar los difrentes estados de la UI (diferentes historias) con este simple componente button en vez de hacerlo con el componente de la librería, este componente no va a usarse !

2022-08-19 23:21 UTC, aledeloss commented on stories/Tabs/Tabs.tsx
> +  const [events] = useState([
Este array de eventos hardcodeados podría estar en otro archivo de constantes o data del componente, para que sea claro y fácil de acceder si eventualmente se quiere actualizar. Es solo una idea para evaluar, pero en cualquier caso, sugiero extraerlo a una constante :)

2022-08-20 16:36 UTC, JairDev commented on stories/Tabs/Tabs.tsx
> +  const [events] = useState([
Hola Ale, sí, voy a separar los datos del componente, también nikka lo sugirió, gracias bro !

2022-08-20 16:37 UTC, JairDev commented on stories/Tabs/Tabs.tsx
> +  const [events] = useState([
Aunque, claro estos datos deben venir de algún servicio, no ?

2022-08-22 15:56 UTC, nykka commented on stories/ButtonTabs/ButtonTabs.tsx
> +export const ButtonTabs = ({ states = "active" }: ButtonTabsProps) => {
Creo que seria mejor no tener componentes que no vamos a usar solo para mostrar los diferentes estados. Éstos deberian ser testeados en el story de Storybook interactuando con el componente.

2022-08-22 16:03 UTC, nykka commented on stories/Tabs/Tabs.stories.tsx
> +const Template: ComponentStory<typeof Tabs> = () => <Tabs events={events} />;
Mucho mejor tener el estado separado del componente. El único problema ahora es que, en su uso, no vamos a pasar un simple string. Si miras los wireframes vas a ver que el contenido de cada tab va a ser bastante complejo (una lista de cards, una tabla, etc) por lo que esta resolución va a volverse engorrosa (imaginate pasar toda esa información via props).
Lo ideal en estos casos es armar varios componentes (uno para las tabs, otro para los paneles, etc) y que cuando creemos las vistas podamos usarlos todos directamente. Al armarlo de esa manera, el template de Storybook quedaría algo así:
`<Tabs>
   <TabsList>
     <Tab>....</Tab>
     <Tab>....</Tab>
   </TabsList>
   <Panels>
     <Panel> ... </Panel>
     <Panel> ... </Panel>
   </Panels>
</Tabs>
`
Se que se ve muy parecido al componente de Headless UI, el trabajo acá es más un tema de estilos y de simplificación.

2022-08-22 18:09 UTC, JairDev commented on stories/Tabs/Tabs.stories.tsx
> +const Template: ComponentStory<typeof Tabs> = () => <Tabs events={events} />;
Hola nykka, pero estos props no es solo la info que consumirían los componente cards, table, etc? 
 `
const events = [
   {
      type: "Todos",
      eventName: "Todos",
      date: "12-4-2022",
      title: "Todos los eventos",
      disabled: false,
    },
]

const Card = ({ eventName, date }) => {
  return (
    <>
      <div>{eventName}</div>
      <div>{date}</div>
    </>
  );
};

...

<Tab.Panels className="mt-4">
    {events.map(({ eventName, date }) => (
      <Tab.Panel key={eventName}>
        <Card eventName={eventName} data={date}/>
      </Tab.Panel>
    ))}
</Tab.Panels>
`

2022-08-29 16:34 UTC, JairDev commented
Con este hook se puede comprobar que un componente sea utilizado correctamente, ya que la librería no proporciona un error para los componentes hijos, en la librería se pueden usar los componentes así:
`
<Tab.Group>
      <Tab>Tab 1</Tab>
      <Tab>Tab 2</Tab>
      <Tab.Panel>Panel 1</Tab.Panel>
      <Tab.Panel>Panel 2</Tab.Panel>
</Tab.Group>
`
en este caso vemos que se puede llamar un componente Tab sin un componente padre Tab.List
en nuestro caso me quise asegurar de llamarlos de esta manera:

<TabsList> <Tab> 
<TabsPanels> <TabsPanel>

ya que en el caso de <TabsList> este proporciona unos estilos 
`<Tab.List className="flex space-x-4">{children}</Tab.List>`
entonces si el Tabs se llamara sin un TabList rompería el diseño, es una manera de asegurarnos por si se nos olvida.

2022-08-29 16:35 UTC, JairDev commented
Con este hook se puede comprobar que un componente sea utilizado correctamente, ya que la librería no proporciona un error para los componentes hijos, en la librería se pueden usar los componentes así:
`
<Tab.Group> <Tab>Tab 1</Tab> <Tab>Tab 2</Tab> <Tab.Panel>Panel 1</Tab.Panel> 
`
<Tab.Panel>Panel 2</Tab.Panel> </Tab.Group>
en este caso vemos que se puede llamar un componente Tab sin un componente padre Tab.List
en nuestro caso me quise asegurar de llamarlos de esta manera:


ya que en el caso de este proporciona unos estilos
<Tab.List className="flex space-x-4">{children}</Tab.List>
entonces si el Tabs se llamara sin un TabList rompería el diseño, es una manera de asegurarnos por si se nos olvida.

2022-08-29 16:40 UTC, JairDev commented
Con este hook se puede comprobar que un componente sea utilizado correctamente, ya que la librería no proporciona un error para los componentes hijos, en la librería se pueden usar los componentes así:
```
<Tab.Group>
    <Tab>Tab 1</Tab>
    <Tab>Tab 2</Tab> 
    <Tab.Panel>Panel 1</Tab.Panel>
   <Tab.Panel>Panel 2</Tab.Panel> 
</Tab.Group>
```
en este caso vemos que se puede llamar un componente Tab sin un componente padre Tab.List
en nuestro caso me quise asegurar de llamarlos de esta manera:

```
<TabsList>
   <Tab>
   ...
```
ya que en el caso de <TabsList> este proporciona unos estilos
`<Tab.List className="flex space-x-4">{children}</Tab.List>`
entonces si el Tabs se llamara sin un TabList rompería el diseño, es una manera de asegurarnos por si se nos olvida, ademas de proporcionar una estructura.

2022-08-30 19:09 UTC, franmper reviewed
Me parece genial todo el trabajo que hiciste @JairDev ! 

Dejo dos cositas
1- Podriamos escribir alguna documentación de como usar este componenten? que componentes necesita pasarle? Como se usa en general?
2- Aca no estoy 100% seguro de que este sea el comportamiento correcto, pero al tratar de navegar con el `tab` y el teclado no puedo navegar entre tabs, me manda de la tab activa al contenido.

2022-08-30 19:09 UTC, franmper commented on stories/TabsGroup/Tabs.stories.tsx
> +  </TabsGroup>
Podriamos escribir alguna documentacion en notion o algo que ayude a utilizar este componente, por que creo que si lo agarra otra persona va a estar muy confundida.

2022-09-01 18:13 UTC, franmper approved these changes

2022-09-01 19:30 UTC, franmper approved these changes

2022-09-06 00:49 UTC, franmper approved these changes

2022-09-06 20:09 UTC, nykka approved these changes
LGTM!!!

2022-09-07 16:55 UTC, merged